//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.11 at 12:57:29 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.mayuratech.demo", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mayuratech.demo;
